const speciesList = [
  "Abies concolor (White Fir)",
  "Abies grandis (Grand Fir)",
  "Acer ginnala (Amur Maple)",
  "Acer macrophyllum (Bigleaf Maple)",
  "Acer negundo (Boxelder)",
  "Acer palmatum (Japanese Maple)",
  "Acer platanoides (Norway Maple)",
  "Acer rubrum (Red Maple)",
  "Acer saccharinum (Silver Maple)",
  "Acer saccharum (Sugar Maple)",
  "Aesculus californica (California Buckeye)",
  "Aesculus hippocastanum (Horsechestnut)",
  "Ailanthus altissima (Tree-of-Heaven)",
  "Alnus rubra (Red Alder)",
  "Arbutus menziesii (Pacific Madrone)",
  "Betula nigra (River Birch)",
  "Betula papyrifera (Paper Birch)",
  "Betula pendula (European White Birch)",
  "Calocedrus decurrens (Incense Cedar)",
  "Carpinus caroliniana (American Hornbeam)",
  "Carya illinoinensis (Pecan)",
  "Catalpa speciosa (Northern Catalpa)",
  "Cedrus atlantica (Atlas Cedar)",
  "Cedrus deodara (Deodar Cedar)",
  "Celtis occidentalis (Common Hackberry)",
  "Cercis canadensis (Eastern Redbud)",
  "Chamaecyparis lawsoniana (Port Orford Cedar)",
  "Cornus florida (Flowering Dogwood)",
  "Cornus nuttallii (Pacific Dogwood)",
  "Crataegus laevigata (English Hawthorn)",
  "Cupressus macrocarpa (Monterey Cypress)",
  "Fagus grandifolia (American Beech)",
  "Fagus sylvatica (European Beech)",
  "Fraxinus americana (White Ash)",
  "Fraxinus latifolia (Oregon Ash)",
  "Fraxinus pennsylvanica (Green Ash)",
  "Ginkgo biloba (Ginkgo)",
  "Gleditsia triacanthos (Honeylocust)",
  "Juglans hindsii (California Black Walnut)",
  "Juglans nigra (Black Walnut)",
  "Juniperus scopulorum (Rocky Mountain Juniper)",
  "Juniperus virginiana (Eastern Redcedar)",
  "Larix decidua (European Larch)",
  "Liquidambar styraciflua (American Sweetgum)",
  "Liriodendron tulipifera (Tulip Tree)",
  "Magnolia grandiflora (Southern Magnolia)",
  "Malus spp. (Crabapple)",
  "Metasequoia glyptostroboides (Dawn Redwood)",
  "Morus alba (White Mulberry)",
  "Nyssa sylvatica (Black Gum)",
  "Picea abies (Norway Spruce)",
  "Picea pungens (Colorado Blue Spruce)",
  "Pinus canariensis (Canary Island Pine)",
  "Pinus contorta (Lodgepole Pine)",
  "Pinus nigra (Austrian Pine)",
  "Pinus ponderosa (Ponderosa Pine)",
  "Pinus radiata (Monterey Pine)",
  "Pinus strobus (Eastern White Pine)",
  "Pinus sylvestris (Scots Pine)",
  "Pinus thunbergii (Japanese Black Pine)",
  "Platanus × hispanica (London Planetree)",
  "Platanus occidentalis (American Sycamore)",
  "Platanus racemosa (California Sycamore)",
  "Populus alba (White Poplar)",
  "Populus balsamifera (Balsam Poplar)",
  "Populus deltoides (Eastern Cottonwood)",
  "Populus nigra 'Italica' (Lombardy Poplar)",
  "Populus tremuloides (Quaking Aspen)",
  "Prunus cerasifera (Cherry Plum)",
  "Prunus serotina (Black Cherry)",
  "Prunus virginiana (Chokecherry)",
  "Pseudotsuga menziesii (Douglas-fir)",
  "Pyrus calleryana (Callery Pear)",
  "Quercus agrifolia (Coast Live Oak)",
  "Quercus alba (White Oak)",
  "Quercus chrysolepis (Canyon Live Oak)",
  "Quercus coccinea (Scarlet Oak)",
  "Quercus douglasii (Blue Oak)",
  "Quercus garryana (Oregon White Oak)",
  "Quercus kelloggii (California Black Oak)",
  "Quercus lobata (Valley Oak)",
  "Quercus macrocarpa (Bur Oak)",
  "Quercus palustris (Pin Oak)",
  "Quercus phellos (Willow Oak)",
  "Quercus rubra (Northern Red Oak)",
  "Quercus velutina (Black Oak)",
  "Quercus wislizeni (Interior Live Oak)",
  "Robinia pseudoacacia (Black Locust)",
  "Salix babylonica (Weeping Willow)",
  "Salix lasiolepis (Arroyo Willow)",
  "Sambucus nigra (Elderberry)",
  "Sequoia sempervirens (Coast Redwood)",
  "Sequoiadendron giganteum (Giant Sequoia)",
  "Sorbus aucuparia (European Mountain-ash)",
  "Taxodium distichum (Bald Cypress)",
  "Thuja plicata (Western Redcedar)",
  "Tilia americana (American Linden)",
  "Tilia cordata (Littleleaf Linden)",
  "Tsuga heterophylla (Western Hemlock)",
  "Ulmus americana (American Elm)",
  "Ulmus parvifolia (Chinese Elm)",
  "Ulmus pumila (Siberian Elm)",
  "Umbellularia californica (California Bay Laurel)"
];

export default speciesList;
